global using Microsoft.EntityFrameworkCore;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using Sysx.EntityFramework.SqlServer.Plugins;
global using Sysx.EntityFramework.SqlServer.Testing;
global using Sysx.Identifiers;
global using Xunit;
