global using Microsoft.Extensions.DependencyInjection;
global using System;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Linq;
global using Sysx.JobEngine;
global using Test_Sysx.JobEngine.Assets;
global using Test_Sysx.JobEngine.Jobs;
global using Test_Sysx.JobEngine.OnActionHandlers;
global using Test_Sysx.JobEngine.VoxelEngine;
global using Test_Sysx.JobEngine.VoxelEngine.Assets;
global using Test_Sysx.JobEngine.VoxelEngine.Jobs;
global using Test_Sysx.JobEngine.VoxelEngine.OnActionHandlers;
global using Xunit;
global using static Sysx.JobEngine.AssetContext;
global using static Test_Sysx.JobEngine.VoxelEngine.AssetContextExtensions;
global using static Test_Sysx.JobEngine.VoxelEngine.EngineFactory;