global using Microsoft.Data.Sqlite;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.EntityFrameworkCore.Sqlite.Infrastructure.Internal;
global using System;
global using System.Data.Common;
global using System.Diagnostics;
global using System.IO;
global using SysX.EntityFramework.Testing;
